/// Flutter icons Platform
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Platform
///      fonts:
///       - asset: fonts/Platform.ttf
///
/// 
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class Platform {
  Platform._();

  static const _kFontFam = 'Platform';

  static const IconData attach = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData search = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData settings = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData stethoscope = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData user = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData around = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData auction = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData calendar = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData choices = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData delivery_truck = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData home = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData job_seeker = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData list_1 = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData menu_button = const IconData(0xe80d, fontFamily: _kFontFam);
}
