/// Flutter icons Settings
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Settings
///      fonts:
///       - asset: fonts/Settings.ttf
///
/// 
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class SettingIcons {
  SettingIcons._();

  static const _kFontFam = 'Settings';

  static const IconData attach = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData help = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData language = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData lock = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData outline = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData phone_call = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData smartphone_1 = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData delivery_truck = const IconData(0xe807, fontFamily: _kFontFam);
}
