/// Flutter icons Shopping
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Shopping
///      fonts:
///       - asset: fonts/Shopping.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class Shopping {
  Shopping._();

  static const _kFontFam = 'Shopping';
    static const _kFontMazad= 'MazadIcon';
  static const _shppingIcon = 'ShopIcon';


  static const IconData shopping_bag_01 = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData path_263 = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData swap_vertical = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData fashion = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData furniture = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData malls = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData electronics = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData branding_watermark = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData mobile_message = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData mobile_search = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData mobile_true = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData brightness_2 = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData emptybag = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData logout = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData whislistempty = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData toys = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData baby = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData homeapplicants = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData health = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData shops = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData mobile = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData facebook = const IconData(0xf09a, fontFamily: _kFontFam);
  static const IconData google = const IconData(0xf1a0, fontFamily: _kFontFam);

  //static const IconData supercar = const IconData(0xe800, fontFamily: _kFontMazad);
  static const IconData sedan = const IconData(0xe801, fontFamily: _kFontMazad);
  static const IconData racing_car = const IconData(0xe802, fontFamily: _kFontMazad);
  static const IconData earn = const IconData(0xe803, fontFamily: _kFontMazad);
  static const IconData auction = const IconData(0xe804, fontFamily: _kFontMazad);
  static const IconData edit = const IconData(0xe805, fontFamily: _kFontMazad);
  static const IconData hourglass = const IconData(0xe806, fontFamily: _kFontMazad);
  static const IconData placeholder = const IconData(0xe807, fontFamily: _kFontMazad);

  static const IconData attach = const IconData(0xe800, fontFamily: _shppingIcon);
  static const IconData group_4601 = const IconData(0xe801, fontFamily: _shppingIcon);
  static const IconData shopping_bag = const IconData(0xe802, fontFamily: _shppingIcon);
  static const IconData shopping_bag1 = const IconData(0xe803, fontFamily: _shppingIcon);
  static const IconData mall = const IconData(0xe801, fontFamily: "ShopIcon2");
  static const IconData shop = const IconData(0xe802, fontFamily: "ShopIcon2");
  static const IconData supercar = const IconData(0xe803, fontFamily: "ShopIcon2");
  static const IconData product = const IconData(0xe804, fontFamily: "ShopIcon2");
    static const IconData group_5457 = const IconData(0xe801, fontFamily: "test");

}
