/// Flutter icons UberTypes
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  UberTypes
///      fonts:
///       - asset: fonts/UberTypes.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class UberTypes {
  UberTypes._();

  static const _kFontFam = 'UberTypes';

  static const IconData yatch = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData bike = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData bicycle = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData metro = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData recovery = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData scooter = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData train = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData helicopter = const IconData(0xe807, fontFamily: _kFontFam);
}
