/// Flutter icons ShopIcon
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ShopIcon
///      fonts:
///       - asset: fonts/ShopIcon.ttf
///
/// 
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class ShopIcon {
  ShopIcon._();

  static const _kFontFam = 'ShopIcon';

  static const IconData attach = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData group_5457 = const IconData(0xe801, fontFamily: _kFontFam);
}
