/// Flutter icons Wuzzef
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Wuzzef
///      fonts:
///       - asset: fonts/Wuzzef.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Wuzzef {
  Wuzzef._();

  static const _kFontFam = 'Wuzzef';

  static const IconData share = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData brands_and_logotypes = const IconData(0xe801, fontFamily: _kFontFam);
}
